### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by spudnut2000** [Acueres/SharpCraft#1]
As the project contains no license it cannot be used at all for any purpose, is this the expectation or an oversight? This looks like a cool project and I would like to learn from it!

**Comment by Acueres** [comment]
Hello. Thanks for bringing this up. I'll add a license when I have the
opportunity.

пн, 27 мая 2024 г. в 09:19, Spudnut2000 ***@***.***>:

**Comment by Acueres** [comment]
Added MIT license
